ext {
    GROUPID = 'com.github.MrStahlfelge.gdx-websockets'
    VERSION = '1.9.10.3-SNAPSHOT'
}

allprojects {

    apply plugin: 'maven-publish'

    ext {
        appName = 'gdx-websockets'
        gdxVersion = '1.13.1'
        nvVersion = '2.14'
    }

    repositories {
        mavenCentral()
    }

    group = GROUPID
    version = VERSION

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
    }

    tasks.withType(Test).tap {
        configureEach {
            systemProperty 'file.encoding', 'UTF-8'
        }
    }

}

