allprojects {
    apply plugin: 'java-library'
    apply plugin: 'maven-publish'

    ext {
        appName = 'gdx-websockets'
        gdxVersion = '1.14.2'
        nvVersion = '2.14'
        teavmVersion = '0.14.0'
    }

    repositories {
        mavenCentral()
    }

    group = 'com.github.IvanVatov.gdx-websockets'
    version = '1.11.0'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(17)
        }
    }

    tasks.register('sourcesJar', Jar) {
        from sourceSets.main.allSource
        archiveClassifier.set('sources')
    }

    afterEvaluate {
        publishing {
            publications {
                create("mavenJava", MavenPublication) {
                    from components.java
                    artifact sourcesJar
                }
            }
        }
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
    }

    tasks.withType(Test).tap {
        configureEach {
            systemProperty 'file.encoding', 'UTF-8'
        }
    }
}

