apply plugin: 'java-library'

configurations {
    custom
    compile.extendsFrom custom
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }
}

dependencies {
    implementation "com.badlogicgames.gdx:gdx:$gdxVersion"
}

ext {
    ARTIFACTID = 'gdx-controllers-core'
}

tasks.register('sourcesJar', Jar) {
    dependsOn classes
    archiveClassifier.set('sources')
    from sourceSets.main.allSource
}

artifacts {
    archives sourcesJar
}