apply plugin: 'java-library'

javadoc {
  options.addStringOption("sourcepath", "")
}

dependencies {
  api project(":core")
  implementation "com.badlogicgames.gdx:gdx-backend-gwt:$gdxVersion"
  implementation "com.badlogicgames.gdx:gdx:$gdxVersion:sources"
  implementation "com.badlogicgames.gdx:gdx-backend-gwt:$gdxVersion:sources"
}

tasks.register('sourcesJar', Jar) {
  dependsOn classes
  archiveClassifier.set('sources')
  from sourceSets.main.allSource
}

artifacts {
  archives sourcesJar
}